spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lastsecond_flight
    username: postgres
    password: 2212
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml  # Ensure this path is correct

server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/baeldung.p12
    key-store-password: 221209
    key-alias: baeldung
  port: 8443
